[project]
name = "bwu-clipboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas==1.5.3",
]

[tool.poetry]
packages = [
    { include = "bwu_clipboard" }
]
